### ISSUE TITLE
OpenZipkin nuget account for releasing packages

### ISSUE THREAD

**Issue by aliostad** [openzipkin/zipkin-csharp#23]
@adriancole to action

**Comment by adriancole** [comment]
cc @openzipkin/devops-tooling just in case someone else wants to help :)

**Comment by aliostad** [comment]
It is frankly just opening an account in the http://www.nuget.org website :)

**Comment by adriancole** [comment]
@aliostad please keep in mind that I support over a dozen projects. I humbly ask you to engage others instead of assuming I will do all sorts of review, cleanup, and administrative work personally. This includes asking on lists instead of me personally, and also soliciting users to review your work. It isn't sustainable to take my time for granted on all tasks.

**Comment by adriancole** [comment]
@aliostad so I've sent you a secure note for the password to the openzipkin nuget account.

Please don't publish this as a 1.0 (or otherwise formal release) since no-one who uses .net has participated in any recent issue or even agreed to test this, yet. If there's a snapshot ability, please use that.

Once there's feedback from users, it would be time to think about 1.0, but until then, let's keep it flexible.

**Comment by aliostad** [comment]
Thank you!

> Please don't publish this as a 1.0 

Sure :) After doing OSS for more than 5 years I think I have learnt a thing or two about versioning. My most popular project (cachecow) went to version 1.0 after 2.5 years. @adriancole
